# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-08 14:04
from __future__ import unicode_literals

from django.db import migrations
from django.db.utils import IntegrityError
from django.db import transaction
from datetime import datetime

def create_off_days(apps, schema_editor):
    DayOff = apps.get_model('facilities', 'DayOff')
    days_off = [
        ("20190101","Jour de l’An"),
        ("20190422","Pâques"),
        ("20190501","Fête du Travail"),
        ("20190508","Victoire des Alliés en 1945"),
        ("20190530","Ascension"),
        ("20190610","Pentecôte"),
        ("20190714","Fête nationale"),
        ("20190815","Assomption"),
        ("20191101","Toussaint"),
        ("20191111","Armistice 1918"),
        ("20191225","Noël"),

        ("20200101","Jour de l’An"),
        ("20200413","Pâques"),
        ("20200501","Fête du Travail"),
        ("20200508","Victoire des Alliés en 1945"),
        ("20200521","Ascension"),
        ("20200601","Pentecôte"),
        ("20200714","Fête nationale"),
        ("20200815","Assomption"),
        ("20201101","Toussaint"),
        ("20201111","Armistice 1918"),
        ("20201225","Noël"),

        ("20210101","Jour de l’An"),
        ("20210405","Pâques"),
        ("20210501","Fête du Travail"),
        ("20210508","Victoire des Alliés en 1945"),
        ("20210513","Ascension"),
        ("20210524","Pentecôte"),
        ("20210714","Fête nationale"),
        ("20210815","Assomption"),
        ("20211101","Toussaint"),
        ("20211111","Armistice 1918"),
        ("20211225","Noël"),
    ]

    for d, name in days_off:
        try:
            with transaction.atomic():
                DayOff.objects.create(date=datetime.strptime(d, "%Y%m%d").date(), desc=name)
        except IntegrityError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_auto_20191126_1843'),
    ]

    operations = [
        migrations.RunPython(create_off_days),
    ]
