# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_auto_20191208_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayoff',
            options={'ordering': ('date',)},
        ),
    ]
