# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hostings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('zipcode', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('web', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('food', models.BooleanField(default=False)),
                ('picnic', models.CharField(max_length=1)),
                ('car_parking', models.BooleanField(default=False)),
                ('cycle_garage', models.BooleanField(default=False)),
                ('stable', models.BooleanField(default=False)),
                ('disabled_access', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('booking_phone_only', models.BooleanField(default=False)),
                ('food_shop', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('tumble_drier', models.BooleanField(default=False)),
                ('sheet_renting', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('jacuzzi', models.BooleanField(default=False)),
                ('bivouac', models.BooleanField(default=False)),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HostingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('public_holiday', models.BooleanField(default=False)),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostings.Hostings')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='hostings',
            name='accepted_payments',
            field=models.ManyToManyField(to='hostings.PaymentType'),
        ),
        migrations.AddField(
            model_name='hostings',
            name='hosting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostings.HostingType'),
        ),
        migrations.AddField(
            model_name='hostings',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
        migrations.AddField(
            model_name='contact',
            name='hosting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostings.Hostings'),
        ),
    ]
