# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 10:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arret', models.CharField(max_length=64)),
                ('gps', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.DateTimeField()),
                ('arret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Arret')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeCirculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(choices=[('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi'), ('6', 'Samedi'), ('7', 'Dimanche ou jours feries'), ('8', 'Vacances Scolaire'), ('9', 'Hors Vacances')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_titre', models.CharField(choices=[('A', 'Abonnement'), ('T', 'Ticket')], max_length=1)),
                ('prix', models.FloatField()),
                ('validiter', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.PeriodeCirculation')),
            ],
        ),
        migrations.AddField(
            model_name='horaire',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Trajet'),
        ),
    ]
