# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
from decimal import *

class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arret',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal(1), max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arret',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal(1), max_digits=10),
            preserve_default=False,
        ),
    ]
