# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 08:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostings',
            name='geo_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
