# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='line',
            new_name='route',
        ),
    ]
