# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostings', '0002_hostings_geo_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleeping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bed1place', models.FloatField(blank=True)),
                ('bed2place', models.FloatField(blank=True)),
                ('wc_where', models.BooleanField(default=True)),
                ('sanitation', models.CharField(choices=[('1', 'Douche'), ('2', 'Baignoire'), ('3', 'Douche + Baignoire')], default=1, max_length=1)),
                ('sanitation_where', models.BooleanField(default=True)),
                ('comments', models.TextField()),
                ('breakfast', models.CharField(choices=[('1', 'OUI'), ('2', 'NON'), ('3', 'A LA DEMANDE')], default=1, max_length=1)),
                ('breakfast_price', models.FloatField(blank=True, null=True)),
                ('half_board', models.CharField(choices=[('1', 'OUI'), ('2', 'NON'), ('3', 'A LA DEMANDE')], default=1, max_length=1)),
                ('half_board_price', models.FloatField(blank=True, null=True)),
                ('price_1person', models.FloatField(blank=True, null=True)),
                ('price_Xperson', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SleepingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='hostings',
            name='picnic_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostings',
            name='max_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostings',
            name='min_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostings',
            name='picnic',
            field=models.CharField(choices=[('1', 'OUI'), ('2', 'NON'), ('3', 'A LA DEMANDE')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='sleeping',
            name='hosting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostings.Hostings'),
        ),
        migrations.AddField(
            model_name='sleeping',
            name='sleeping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostings.SleepingType'),
        ),
    ]
