# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:36
from __future__ import unicode_literals

from django.db import migrations


def populate_poi_types(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    POIType = apps.get_model("itinerary", "POIType")
    poi_types = ["Hôtel", "Restaurant", "Épicerie"]

    for poi_type in poi_types:
        POIType.objects.create(label=poi_type)


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_poitype'),
    ]

    operations = [
        migrations.RunPython(populate_poi_types),
    ]
