# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models
from decimal import *

class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_auto_20160510_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='arret',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal(1), max_digits=10),
        ),
        migrations.AddField(
            model_name='arret',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal(1), max_digits=10),
        ),
    ]
