# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

# def populate_poi(apps, schema_editor):
#     POI = apps.get_model("itinerary", "POI")
#     POIType = apps.get_model("itinerary", "POIType")
#
#     POI.objects.get_or_create(name="Test",
#                               description="Test desc.",
#                               type=POIType.objects.get(id=1))
#
#
# def backward_func(apps, schema_editor):
#     pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('itinerary', '0004_poiaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_itinerary.poi_set+', to='contenttypes.ContentType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.POIType')),
            ],
            options={
                'abstract': False,
            },
        ),
        # migrations.RunPython(populate_poi, backward_func),
    ]
