# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostings', '0006_auto_20170309_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostings',
            old_name='geo_coordinates',
            new_name='geom',
        ),
    ]
