# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_auto_20160510_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arret',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='arret',
            name='longitude',
        ),
    ]
