# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostings', '0007_auto_20170323_1730'),
        ('poimap', '0004_poiaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostings',
            name='hosting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poimap.POIType'),
        ),
        migrations.DeleteModel(
            name='HostingType',
        ),
    ]
