# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0008_auto_20160510_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodecirculation',
            name='choix',
            field=models.CharField(choices=[('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi'), ('6', 'Samedi'), ('7', 'Dimanche ou jours feries'), ('8', 'Vacances Scolaire'), ('9', 'Hors Vacances')], max_length=1, unique=True),
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='periode',
        ),
        migrations.AddField(
            model_name='trajet',
            name='periode',
            field=models.ManyToManyField(to='transportation.PeriodeCirculation'),
        ),
    ]
