# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_poi'),
        ('hostings', '0008_auto_20170327_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostings',
            name='id',
        ),
        migrations.AddField(
            model_name='hostings',
            name='poi_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itinerary.POI'),
            preserve_default=False,
        ),
    ]
