# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostings', '0009_auto_20170329_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hostings',
            name='hosting_type',
        ),
        migrations.RemoveField(
            model_name='hostings',
            name='name',
        ),
    ]
