# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0009_auto_20160510_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaire',
            name='heure',
            field=models.TimeField(),
        ),
    ]
