# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 08:01
from __future__ import unicode_literals

import autoslug.fields
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0010_auto_20160510_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arret',
            old_name='arret',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='arret',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='slug', editable=False, populate_from='nom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arret',
            name='gps',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
