# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 08:54
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0011_auto_20160524_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='slug', editable=False, populate_from='nom'),
            preserve_default=False,
        ),
    ]
