# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0013_auto_20160613_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarif',
            new_name='Fare',
        ),
    ]
