# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0014_auto_20170711_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fare',
            old_name='prix',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='fare',
            old_name='type_titre',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='fare',
            old_name='validiter',
            new_name='valid_for',
        ),
    ]
