# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0016_auto_20170711_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runningday',
            old_name='choix',
            new_name='period',
        ),
    ]
