# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:32
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0018_auto_20170711_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='nom',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='stop',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
