# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0019_auto_20170711_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trajet',
            new_name='Route',
        ),
    ]
