# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:50
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0020_auto_20170711_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horaire',
            new_name='TimeSlot',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='nom',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='route',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
