# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0021_auto_20170711_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ('hour',)},
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='heure',
            new_name='hour',
        ),
    ]
