# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0022_auto_20170712_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='arret',
            new_name='stop',
        ),
    ]
