# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0023_auto_20170712_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='trajet',
            new_name='route',
        ),
    ]
