# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0031_auto_20170605_2155'),
        ('transportation', '0024_auto_20170712_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='poi_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poimap.POI'),
        ),
    ]
