# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 11:59
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.gis.geos import GEOSGeometry

def create_poi(apps, schema_editor):
    Stop = apps.get_model('transportation', 'Stop')
    POI = apps.get_model('poimap', 'POI')
    POIType = apps.get_model('poimap', 'POIType')
    for stop in Stop.objects.all():
        wkt = "POINT (%s %s 0)" % (stop.gps.x, stop.gps.y)
        point = GEOSGeometry(wkt)
        poi = POI.objects.create(name=stop.name, geom=point, type=POIType.objects.get_or_create(label="default")[0])
        stop.poi_id = poi

class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0025_stop_poi_id'),
    ]

    operations = [
        migrations.RunPython(create_poi),
    ]
