# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0026_create_stop_poi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='name',
        ),
    ]
