# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 12:38
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0028_auto_20170712_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='LineStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Line')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Stop')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='line',
            name='stops',
            field=models.ManyToManyField(through='transportation.LineStop', to='transportation.Stop'),
        ),
    ]
