# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0029_auto_20170715_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transportation.Line'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='hour',
            field=models.TimeField(null=True),
        ),
    ]
