# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0031_auto_20170715_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='transportation.Route'),
        ),
    ]
