# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 20:02
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poimap', '0031_auto_20170605_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Abonnement'), ('T', 'Ticket')], max_length=1)),
                ('price', models.FloatField()),
                ('valid_for', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='LineStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('1', 'Aller'), ('2', 'Retour')], max_length=1)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Line')),
            ],
        ),
        migrations.CreateModel(
            name='RunningDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1', 'Lundi'), ('2', 'Mardi'), ('3', 'Mercredi'), ('4', 'Jeudi'), ('5', 'Vendredi'), ('6', 'Samedi'), ('7', 'Dimanche ou jours feries'), ('8', 'Vacances Scolaire'), ('9', 'Hors Vacances')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='transportation.Route')),
                ('periode', models.ManyToManyField(to='transportation.RunningDay')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('poi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poimap.POI')),
            ],
            options={
                'abstract': False,
            },
            bases=('poimap.poi',),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='transportation.Service')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Stop')),
            ],
            options={
                'ordering': ('hour', 'order'),
            },
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(through='transportation.LineStop', to='transportation.Stop'),
        ),
        migrations.AddField(
            model_name='linestop',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Route'),
        ),
        migrations.AddField(
            model_name='linestop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Stop'),
        ),
    ]
