# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_auto_20170716_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop', to='transportation.Stop'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('line', 'direction')]),
        ),
    ]
