# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_auto_20180220_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('id', 'direction')},
        ),
    ]
