# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_auto_20180220_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='periode',
        ),
    ]
