# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0008_remove_service_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='frequency_label',
            field=models.CharField(default='--------', max_length=10),
            preserve_default=False,
        ),
    ]
