# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0049_auto_20180215_1652'),
        ('transportation', '0009_service_frequency_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='route',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poimap.Path'),
        ),
        migrations.AlterField(
            model_name='route',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transportation.Line'),
        ),
    ]
