# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 07:41
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0010_auto_20180221_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
    ]
