# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0011_service_recurrences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='service',
            name='recurrences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
