# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0013_service_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField()),
                ('stop1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_edges', to='transportation.Stop')),
                ('stop2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_edges', to='transportation.Stop')),
            ],
        ),
    ]
