# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0015_graphedge_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphedge',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
