# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0017_delete_runningday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraphEdge',
            new_name='Travel',
        ),
    ]
