# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0019_delete_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
