# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0020_travel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
