# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0022_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=500, unique=True)),
                ('traveller_first_name', models.CharField(max_length=255)),
                ('traveller_last_name', models.CharField(max_length=255)),
                ('departure_hour', models.TimeField()),
                ('arrival_hour', models.TimeField()),
                ('seat_number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('arrival_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_departure_stops', to='transportation.Stop')),
                ('departure_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_arrival_stops', to='transportation.Stop')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Order')),
            ],
        ),
    ]
