# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0025_auto_20180602_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
