# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-11 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0026_ticket_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='optin',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='privacy',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='terms',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
