# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0029_ticket_connections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='service',
        ),
    ]
