# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-18 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.folder
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('transportation', '0031_auto_20180614_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='cover',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='bus',
            name='gallery',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='filer.Folder'),
        ),
        migrations.AddField(
            model_name='bus',
            name='index_eco',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bus',
            name='nb_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bus',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
