# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0034_line_connection_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateTimeField()),
                ('partner', models.CharField(max_length=200)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('arrival_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transportation.Stop')),
                ('departure_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transportation.Stop')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrival_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_arrival_stops', to='transportation.Stop'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_departure_stops', to='transportation.Stop'),
        ),
    ]
