# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 13:01
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0036_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True),
        ),
    ]
