# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 12:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0038_auto_20180720_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ('stop1__name', 'stop2__name')},
        ),
        migrations.AddField(
            model_name='bus',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
