# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0040_auto_20180827_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
