# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 10:19
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        ('transportation', '0041_auto_20180923_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='prices',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
