# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0042_line_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
