# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0043_bus_license_plate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('last_name', 'first_name', 'email')},
        ),
        migrations.AddField(
            model_name='partnersearch',
            name='info',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
