# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0044_auto_20181217_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ('stop1__name', 'distance')},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_next_day',
            field=models.BooleanField(default=False),
        ),
    ]
