# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0045_auto_20190114_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='00000000000', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_notif',
            field=models.BooleanField(default=False),
        ),
    ]
