# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-03 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0047_smsnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotification',
            name='phonebook_contact_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
