# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-04 10:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0048_smsnotification_phonebook_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotification',
            name='future_sms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
