# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0049_smsnotification_future_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('message', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Service')),
            ],
        ),
    ]
