# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0050_smsannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('access_driver_infos', 'Access to driver infos'), ('access_sms_announcement', 'Access SMS announcement form')),
            },
        ),
    ]
