# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0051_custompermissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsnotification',
            name='phonebook_contact_id',
        ),
    ]
