# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0052_remove_smsnotification_phonebook_contact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsannouncement',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
