# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0053_auto_20190305_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsannouncement',
            name='departure_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsannouncement',
            name='notification_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
