# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0054_auto_20190305_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsannouncement',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='smsannouncement',
            name='departure_time',
        ),
    ]
