# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-08 06:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0055_auto_20190305_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnotification',
            name='future_sms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
