# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-02 13:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0056_auto_20190408_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('date', 'departure_hour')},
        ),
        migrations.AddField(
            model_name='bus',
            name='confort',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='security',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
