# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-26 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0057_auto_20191002_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='days_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='from_date',
            field=models.DateField(default=datetime.date(2019, 11, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='to_date',
            field=models.DateField(default=datetime.date(2019, 11, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
