# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-08 14:10
from __future__ import unicode_literals

from django.db import migrations
from datetime import datetime
from dateutil.rrule import rrule, rruleset, WEEKLY, MO, TU, WE, TH, FR, SA, SU

def migrate_service_ruleset(apps, schema_editor):
    Service = apps.get_model('transportation', 'Service')
    for service in Service.objects.all():
        service.monday = service.frequency_label[0] == 'L'
        service.tuesday = service.frequency_label[1] == 'M'
        service.wednesday = service.frequency_label[2] == 'M'
        service.thursday = service.frequency_label[3] == 'J'
        service.friday = service.frequency_label[4] == 'V'
        service.saturday = service.frequency_label[5] == 'S'
        service.sunday = service.frequency_label[6] == 'D'
        service.days_off = service.frequency_label[7] == 'F'
        

        rule_str = [r for r in service.recurrences.split("|")][0].replace("\r", ";").split(";")
        from_date = rule_str[0].replace("DTSTART:", "").replace("T000000Z", "")
        to_date = rule_str[2].replace("UNTIL=", "").replace("T000000Z", "")

        from_date = datetime.strptime(from_date, "%Y%m%d").date()
        to_date = datetime.strptime(to_date, "%Y%m%d").date()

        service.from_date = from_date
        service.to_date = to_date
        
        weekdays = []
        if service.monday:
            weekdays.append(MO)
        if service.tuesday: 
            weekdays.append(TU)
        if service.wednesday: 
            weekdays.append(WE)
        if service.thursday: 
            weekdays.append(TH)
        if service.friday: 
            weekdays.append(FR)
        if service.saturday: 
            weekdays.append(SA) 
        if service.sunday:    
            weekdays.append(SU) 

        service.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0058_auto_20191126_1741'),
    ]

    operations = [
        migrations.RunPython(migrate_service_ruleset),
    ]
