# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0059_auto_20191208_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='days_off',
            field=models.BooleanField(default=False, verbose_name='F\xe9ri\xe9s'),
        ),
        migrations.AlterField(
            model_name='service',
            name='friday',
            field=models.BooleanField(default=False, verbose_name='Vendredi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active ?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_temporary',
            field=models.BooleanField(default=False, verbose_name='Temp ?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='monday',
            field=models.BooleanField(default=False, verbose_name='Lundi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='Samedi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='Dimanche'),
        ),
        migrations.AlterField(
            model_name='service',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name='Jeudi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name='Mardi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name='Mercredi'),
        ),
    ]
