# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-04 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0061_service_include'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceWorkingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=False, verbose_name='Lundi')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Mardi')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Mercredi')),
                ('thursday', models.BooleanField(default=False, verbose_name='Jeudi')),
                ('friday', models.BooleanField(default=False, verbose_name='Vendredi')),
                ('saturday', models.BooleanField(default=False, verbose_name='Samedi')),
                ('sunday', models.BooleanField(default=False, verbose_name='Dimanche')),
                ('days_off', models.BooleanField(default=False, verbose_name='F\xe9ri\xe9s')),
                ('include', models.BooleanField(default=True, verbose_name='Inclure/Exclure ?')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='include',
            field=models.BooleanField(default=True, verbose_name='Inclure/Exclure ?'),
        ),
        migrations.AddField(
            model_name='serviceworkingperiod',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_periods', to='transportation.Service'),
        ),
    ]
