# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-01 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0063_line_carbon_footprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
