# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0064_line_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('last_name', 'first_name', 'email'), 'verbose_name': 'client'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'line'},
        ),
        migrations.AlterModelOptions(
            name='smsannouncement',
            options={'verbose_name': 'annonce SMS', 'verbose_name_plural': 'annonces SMS'},
        ),
        migrations.AlterField(
            model_name='smsannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='cr\xe9\xe9 le'),
        ),
        migrations.AlterField(
            model_name='smsannouncement',
            name='departure_datetime',
            field=models.DateTimeField(verbose_name='date/heure de d\xe9part'),
        ),
        migrations.AlterField(
            model_name='smsannouncement',
            name='notification_datetime',
            field=models.DateTimeField(verbose_name='date/heure de la notification'),
        ),
    ]
