# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poimap', '0049_auto_20180215_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poimap.POI')),
            ],
        ),
    ]
