# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
