# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 08:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
