# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('weather', '0003_weather_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='weather_weathercmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('weathers', models.ManyToManyField(to='weather.Weather')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
