# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20180305_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ('poi__distance',)},
        ),
    ]
