# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_poi'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='name',
            field=models.CharField(default='plop', max_length=50),
            preserve_default=False,
        ),
    ]
