# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0006_auto_20170329_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='poiaddress',
            name='poi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itinerary.POI'),
            preserve_default=False,
        ),
    ]
