# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0008_poitype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poiaddress',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='poiaddress',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='poiaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='poitype',
            name='icon',
            field=models.CharField(choices=[(b'flag', b'Drapeau'), (b'cutlery', b'Restaurant'), (b'bed', b'Hotel'), (b'shopping-basket', b'Magasin'), (b'tint', b"Point d'eau")], default=b'flag', max_length=30),
        ),
    ]
