# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0009_auto_20170403_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitype',
            name='icon',
            field=models.CharField(choices=[(b'flag', b'Drapeau'), (b'cutlery', b'Restaurant'), (b'bed', b'Hotel'), (b'shopping-basket', b'Magasin'), (b'tint', b"Point d'eau"), (b'certificate', b'Site touristique')], default=b'flag', max_length=30),
        ),
    ]
