# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0014_auto_20170404_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
