# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0016_auto_20170404_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitype',
            name='icon',
            field=models.CharField(choices=[(b'flag', b'Drapeau'), (b'cutlery', b'Restaurant'), (b'bed', b'Hotel'), (b'shopping-basket', b'Magasin'), (b'tint', b"Point d'eau"), (b'certificate', b'Site touristique'), (b'exclamation', b'Avertissement')], default=b'flag', max_length=30),
        ),
    ]
