# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 14:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0017_auto_20170516_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
