# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0019_auto_20170517_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='path',
        ),
    ]
