# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import polymorphic_tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0020_auto_20170602_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={'ordering': ('tree_id', 'lft')},
        ),
        migrations.AddField(
            model_name='poi',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='poimap.POI'),
        ),
        migrations.AddField(
            model_name='poi',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
