# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0021_auto_20170602_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={},
        ),
        migrations.RemoveField(
            model_name='poi',
            name='level',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='tree_id',
        ),
    ]
