# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 09:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0024_auto_20170603_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(dim=3, srid=4326),
        ),
    ]
