# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 13:50
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0026_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='plop', editable=False, populate_from=(b'name',), unique_with=(b'id',)),
            preserve_default=False,
        ),
    ]
