# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0029_auto_20170604_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={'verbose_name': 'POI', 'verbose_name_plural': 'POI'},
        ),
    ]
