# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 19:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0030_auto_20170605_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='path',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(dim=3, srid=4326),
        ),
        migrations.AlterField(
            model_name='poi',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326),
        ),
    ]
