# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


def fix_slug(apps, schema_editor):
    POI = apps.get_model('poimap', 'POI')
    for poi in POI.objects.all():
        poi.save()

class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0032_auto_20170724_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='default', editable=False, populate_from=b'name'),
            preserve_default=False,
        ),
        migrations.RunPython(fix_slug),
    ]
