# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:30
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


def fix_slug(apps, schema_editor):
    POIType = apps.get_model('poimap', 'POIType')
    for poi_type in POIType.objects.all():
        poi_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0033_poi_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitype',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='default', editable=False, populate_from=b'label'),
            preserve_default=False,
        ),
        migrations.RunPython(fix_slug),
    ]
