# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:22
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0034_poitype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
