# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 14:46
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0037_poi_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='path',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='country',
            field=django_countries.fields.CountryField(default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='poi',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='poitype',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='label'),
        ),
    ]
