# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0039_importationtrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importationtrace',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='importationtrace',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
