# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 20:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('poimap', '0040_auto_20180112_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
