# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0041_auto_20180204_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='gallery',
        ),
    ]
