# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 20:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('poimap', '0042_remove_poi_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='gallery',
            field=filer.fields.folder.FilerFolderField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Folder'),
        ),
    ]
