# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-05 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('poimap', '0043_poi_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIListing',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='poimap_poilisting', serialize=False, to='cms.CMSPlugin')),
                ('type_display', models.ManyToManyField(to='poimap.POIType', verbose_name=b'Type de POI \xc3\xa0 afficher')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
