# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-05 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('poimap', '0044_poilisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('file', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='poi',
            name='gallery',
        ),
        migrations.AddField(
            model_name='poimedia',
            name='poi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poimap.POI'),
        ),
    ]
