# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0045_auto_20180205_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poimedia',
            options={'ordering': ['order'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Gallerie'},
        ),
        migrations.AlterField(
            model_name='poimedia',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
