# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0046_auto_20180205_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importationtrace',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
