# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0047_auto_20180208_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poi',
            name='related_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poimap.Path'),
        ),
        migrations.AlterField(
            model_name='poimedia',
            name='poi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='poimap.POI'),
        ),
    ]
