# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0050_poilisting_extra_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poilisting',
            name='extra_placeholder',
        ),
        migrations.AddField(
            model_name='poilisting',
            name='template',
            field=models.CharField(choices=[(b'poimap/partial/poi_map_listing.html', b'Map'), (b'poimap/partial/poi_listing.html', b'List')], default=b'poimap/partial/poi_map_listing.html', max_length=255, verbose_name=b'Template'),
        ),
    ]
