# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 15:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0051_auto_20180305_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
