# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0053_auto_20180321_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='poilisting',
            name='path_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poimap.Path', verbose_name=b'Chemin \xc3\xa0 afficher'),
        ),
    ]
