# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0054_poilisting_path_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='poilisting',
            name='hide_control',
            field=models.BooleanField(default=True),
        ),
    ]
