# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0055_poilisting_hide_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomItineraryFormPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='poimap_customitineraryformplugin', serialize=False, to='cms.CMSPlugin')),
                ('custom_link', models.CharField(blank=True, max_length=2040, verbose_name='Custom link')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Internal link')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
