# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0056_customitineraryformplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poilisting',
            name='template',
            field=models.CharField(choices=[(b'poimap/partial/poi_map_listing.html', b'Map'), (b'poimap/partial/poi_listing.html', b'List'), (b'poimap/partial/itinerary.html', b'Itinerary')], default=b'poimap/partial/poi_map_listing.html', max_length=255, verbose_name=b'Template'),
        ),
    ]
