# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0059_auto_20180323_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poirating',
            options={'ordering': ['-created_at'], 'verbose_name': 'POI', 'verbose_name_plural': 'POI'},
        ),
    ]
