# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0060_auto_20180323_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='poilisting',
            name='area_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poimap.Area', verbose_name=b'Zone \xc3\xa0 afficher'),
        ),
    ]
