# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0061_poilisting_area_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poilisting',
            name='area_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poimap.Area', verbose_name='Zone à afficher'),
        ),
        migrations.AlterField(
            model_name='poilisting',
            name='path_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poimap.Path', verbose_name='Chemin à afficher'),
        ),
        migrations.AlterField(
            model_name='poilisting',
            name='template',
            field=models.CharField(choices=[('poimap/partial/poi_map_listing.html', 'Map'), ('poimap/partial/poi_listing.html', 'List'), ('poimap/partial/itinerary.html', 'Itinerary')], default='poimap/partial/poi_map_listing.html', max_length=255, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='poilisting',
            name='type_display',
            field=models.ManyToManyField(to='poimap.POIType', verbose_name='Type de POI à afficher'),
        ),
    ]
