# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 15:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0062_auto_20180426_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='distance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[{}], null=True),
        ),
    ]
