# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-01 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0067_auto_20180629_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poilisting',
            name='area_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poimap.Area', verbose_name='Zone à afficher'),
        ),
        migrations.AlterField(
            model_name='poilisting',
            name='path_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poimap.Path', verbose_name='Chemin à afficher'),
        ),
        migrations.AlterField(
            model_name='poilisting',
            name='type_display',
            field=models.ManyToManyField(to='poimap.POIType', verbose_name='Type de POI à afficher'),
        ),
    ]
