# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-14 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('poimap', '0070_auto_20181012_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIFilters',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='poimap_poifilters', serialize=False, to='cms.CMSPlugin')),
                ('type_filters', models.ManyToManyField(to='poimap.POIType', verbose_name='Type de POI \xe0 filter')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
