# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0072_auto_20190226_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poimap.POIType'),
        ),
    ]
