# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0073_auto_20190226_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitype',
            name='icon_file',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
