# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0074_auto_20190226_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='types',
            field=models.ManyToManyField(related_name='all_poi', to='poimap.POIType'),
        ),
    ]
