# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-08 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0076_specificpoitypetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificpoitypetemplate',
            name='type',
        ),
        migrations.DeleteModel(
            name='SpecificPOITypeTemplate',
        ),
    ]
