# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0077_auto_20190308_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificPOITypeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_slug', models.CharField(max_length=500)),
                ('template_name', models.CharField(max_length=500)),
            ],
        ),
    ]
