# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0078_specificpoitypetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='altitude',
            field=models.FloatField(default=0.0),
        ),
    ]
