# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0079_poi_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customitineraryformplugin',
            name='important_step_type',
            field=models.ManyToManyField(to='poimap.POIType', verbose_name='Type de \xe9tape importante'),
        ),
    ]
