# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0080_customitineraryformplugin_important_step_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customitineraryformplugin',
            name='important_step_type',
        ),
        migrations.AddField(
            model_name='customitineraryformplugin',
            name='important_step_types',
            field=models.ManyToManyField(to='poimap.POIType', verbose_name='Types de \xe9tapes importantes'),
        ),
    ]
