# -*- coding: utf-8 -*-
# Generated by Django 2.1.10 on 2019-07-15 08:49
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0081_auto_20190516_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importationtrace',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='related_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poimap.Path'),
        ),
        migrations.AlterField(
            model_name='poilisting',
            name='area_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poimap.Area', verbose_name='Zone à afficher'),
        ),
        migrations.AlterField(
            model_name='poilisting',
            name='path_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poimap.Path', verbose_name='Chemin à afficher'),
        ),
        migrations.AlterField(
            model_name='poirating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
