# Generated by Django 2.1.10 on 2019-07-15 08:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0082_auto_20190715_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
