# Generated by Django 2.1.12 on 2019-09-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('poimap', '0083_auto_20190715_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIDetailPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='poimap_poidetailpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poimap.POI')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
