# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('poimap', '0084_poidetailpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='POISearchAutocompletePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='poimap_poisearchautocompletepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('search_types', models.ManyToManyField(to='poimap.POIType', verbose_name='Types de POI recherchés')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
