# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poimap', '0085_poisearchautocompletepluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poilisting',
            name='area_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poimap.Area', verbose_name='Zone \xe0 afficher'),
        ),
        migrations.AlterField(
            model_name='poilisting',
            name='path_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poimap.Path', verbose_name='Chemin \xe0 afficher'),
        ),
        migrations.AlterField(
            model_name='poisearchautocompletepluginmodel',
            name='search_types',
            field=models.ManyToManyField(to='poimap.POIType', verbose_name='Types de POI recherch\xe9s'),
        ),
    ]
