# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostings', '0003_auto_20170309_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeping',
            name='breakfast',
            field=models.CharField(choices=[('1', 'Oui'), ('2', 'Non'), ('3', 'A la demande')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='sleeping',
            name='half_board',
            field=models.CharField(choices=[('1', 'Oui'), ('2', 'Non'), ('3', 'A la demande')], default=1, max_length=1),
        ),
    ]
