# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostings', '0004_auto_20170309_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedSleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(choices=[('1', '1 place'), ('2', '2 places'), ('3', 'Superposes')], default=1, max_length=1)),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='sleeping',
            old_name='sleeping',
            new_name='sleeping_type',
        ),
        migrations.AlterField(
            model_name='hostings',
            name='picnic',
            field=models.CharField(choices=[('1', 'Oui'), ('2', 'Non'), ('3', 'A la demande')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='bedsleep',
            name='sleeping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostings.Sleeping'),
        ),
    ]
