# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostings', '0005_auto_20170309_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedsleep',
            name='sleeping',
        ),
        migrations.RenameField(
            model_name='hostings',
            old_name='picture',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='sleeping',
            name='bed1place',
        ),
        migrations.RemoveField(
            model_name='sleeping',
            name='bed2place',
        ),
        migrations.AddField(
            model_name='sleeping',
            name='places',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BedSleep',
        ),
    ]
