# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-12 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostings', '0011_auto_20170329_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostings',
            name='media',
        ),
    ]
